# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2625bc7a9388b377dc7b947c4b26d11a8496c33ca1bfa61257fc672a43b1863505be00065ca67b101bf3c7977ac424aa071a35dab5448281cdfdd32ba22404f4

test:
  secret_key_base: 0168e0f9feb472c0bd8cdd34d692cf2ee52180417104d74fd77b7978a1ed447328634a1d44ecff5ebc30ed90c3e1791dfe76f222d1f1c29dadc7233809e6749f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
